--- 
abstract: ''
author: ~
build_requires: 
  Catalyst::Runtime: 0
  Test::MockObject: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Devel-ModuleVersions
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 0
  Class::C3: 0
version: 0.0001
